config/routes.rb
Rails.application.routes.draw do

    root to: 'pages#home'
    get '/about', to: 'pages#about'
    get '/admin', to: 'pages#admin'
    
    get '/signup', to: 'users#new'
    resources :users, except: [:new]
    
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    
    resources :chains
    resources :categories
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :chain_categories
    has_many :chains, through: :chain_categories
    validates :name, presence: true, length: { maximum: 50 }
    validates_uniqueness_of :name
end

app/models/chain.rb
class Chain < ActiveRecord::Base
     belongs_to :user
     has_many :chain_categories
     has_many :categories, through: :chain_categories
     validates :name, presence: true, length: { maximum: 50 }
     # validates :user_id, presence: true
     
     def self.search(search)
          if search
               find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
          else
               #find(:all)
          end
     end
     
end

app/models/chain_category.rb
class ChainCategory < ActiveRecord::Base
    belongs_to :chain
    belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
    # attr_accessor :password, :password_confirmation
    before_save { self.email = email.downcase }
    validates :username, presence: true, 
              uniqueness: { case_sensitive: false }, 
              length: { minimum: 3, maximum: 25 }
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
              uniqueness: { case_sensitive: false },
              length: { maximum: 105 },
              format: { with: VALID_EMAIL_REGEX }
    has_secure_password
    # dependent: :destroy means when the user is deleted, so will all of their chains
    has_many :chains, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user    
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
  
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
   before_action :require_admin, only: [:new, :create, :edit, :update, :destroy] 
   
   
    def index
        @categories = Category.all
    end
    
    def new
        @category = Category.new
    end
    
    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:success] = "You have successfully added a new category"
            redirect_to categories_path
        else
            flash[:danger] = "Unable to create new category"
            render 'new'
        end
    end
    
    def edit
        
    end
    
    def update
        
    end
    
    def show
        @category = Category.find(params[:id])
    end
    
    def destroy
    
    end


    private
    def category_params
        params.require(:category).permit(:name)
    end
    
    def require_admin
        if !logged_in? || (logged_in? and !current_user.admin?)
            flash[:danger] = "This action is restricted to admins"
            redirect_to categories_path
        end
    end
    
 
end

app/controllers/chains_controller.rb
class ChainsController < ApplicationController
   before_action :require_user, except: [:index]
   
    def index
        @chains = Chain.paginate(page: params[:page], per_page: 12)
        @chains_search = Chain.search(params[:search])
        # @users = User.paginate(page: params[:page], per_page: 5)
    end
    
    def new
        @chain = Chain.new
    end
    
    def create
        @user = current_user
        @chain = Chain.new(chain_params)
        # Assign user id to Chain table
        @chain.user_id = current_user.id
        if @chain.save
            flash[:success] = "Your chain has been created successfully!"
            redirect_to user_path(@user)
        else
            flash[:danger] = "Error occurred"
            redirect_to new_chain_path
        end
    end
    
    def edit
        @chain = Chain.find(params[:id])
    end
    
    def update
        @chain = Chain.find(params[:id])
        if @chain.update(chain_params)
            flash[:success] = "Chain successfully updated!"
            redirect_to user_path(current_user)
        else
            render 'edit'
        end
    end
    
    def show
       
    end
    
    def destroy
        @user = current_user
        @chain = Chain.find(params[:id])
        if @chain.destroy
            flash[:success] = "Chain was successfully deleted"
            redirect_to user_path(@user)
        else
            flash[:danger] = "Chain unable to be destroyed"
            redirect_to user_path(@user)
        end
    end
   
    private
    def chain_params
        params.require(:chain).permit(:name, :pledge)
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
  def home
      
  end
  
  def about
      
  end
  
  def admin
    @users = User.all
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end
    
    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "You have successfully logged in"
            redirect_to root_path
        else
            flash.now[:danger] = "There was something wrong with your login information"
            render 'new'
        end
    end
    
    def destroy
        session[:user_id] = nil
        flash[:success] = "You have logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.all
    end
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            # This automatically logs the user in on signup
            session[:user_id] = @user.id
            flash[:success] = "Welcome to Goal Positive #{@user.username}"
            redirect_to root_path
        else
            render 'new'
        end
    end
    
    def edit
        
    end
    
    def update
        
    end
    
    def show
        @user = User.find(params[:id])
        @user_chains = @user.chains
    end
    
    def destroy
    
    end
    
    
    private
    def user_params
       params.require(:user).permit(:username, :email, :password, :admin) 
    end
    
    def require_same_user
        if current_user != @user and !current_user.admin?
            flash[:danger] = "You can only edit your own account"
            redirect_to root_path
        end
    end
    
    def require_admin
        if logged_in? and !current_user.admin?
            flash[:danger] = "Only admin users can perform that action"
            redirect_to root_path
        end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<!-- chains_path is the url the form should be submitted to -->
<%= form_for @category, url: categories_path do |f| %>
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class:'form-control', placeholder: "Enter name of new chain" %>
    </div>
    <div class="form-group">
        <%= f.submit "Create Category", class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/categories/index.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <% @categories.each do |category| %>
            <div class="well">
                <strong><%= link_to category.name, category_path(category) %></strong>
                <%= category.created_at %>
                </br>
                <%= pluralize(category.chains.count, "chain") %>
            </div>
        <% end %>
    </div>
</div>

app/views/categories/new.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="well">
            <strong><h1 align="center">Create a New Category</h1></strong>
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/categories/show.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="well">
            <%= @category.name %>
            <%= @category.created_at %>
            <%= @category.updated_at %>
        </div>
    </div>
</div>

app/views/chains/_form.html.erb
<!-- chains_path is the url the form should be submitted to -->
<%= form_for @chain do |f| %>
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class:'form-control', placeholder: "Enter name of new chain" %>
    </div>
    <div class="form-group">
        <%= f.label :pledge %>
        <%= f.text_area :pledge, class: 'form-control', placeholder: "Description" %>
    </div>
    
    <div class="form-group">
        <div class="row">
            <div class="col-md-6 col-md-offset-4">
                <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                    <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
                <% end %>
            </div>
        </div>    
    </div>
    
    <div class="form-group">
        <%= f.submit "Create Chain", class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/chains/edit.html.erb
<h1 align="center">Edit Your Chain - <%= @chain.name %></h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="well">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/chains/index.html.erb
<h1 align="center">All Chains</h1>

<div class="row">
    <div align="center">
        <%= will_paginate %>
    </div>
        <% @chains.each do |chain| %>
            <div class="col-md-1 text-center">
                <div class="well">
                    <strong><%= chain.user.username %></strong>
                    </br>
                    <%= chain.name %>
                    </br>
                    <small><%= chain.pledge %></small>
                </div>
            </div>
        <% end %>
</div>
<div class="row">
    <div align="center">
        <%= will_paginate %>
    </div>
</div>

app/views/chains/new.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="well">
            <strong><h1 align="center">Enter a New Chain!</h1></strong>
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<hr>
<div class="container">
    <footer class="footer">
        <small>
            Copyright &copy; <%= link_to "GoalPositive", root_path %>
        </small>
        <nav class="navbar-right">
            <small align="right">
                <%= link_to "About", about_path %>
            </small>
        </nav>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
    <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{type}" %>
    <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        <i class="fa fa-trophy"></i>
        GoalPositive
        <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Users <span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li><%= link_to "Me", user_path(current_user) %></li>
            <li><%= link_to "All Users", users_path %></li>
        </ul>
        </li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Chains <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Chains", chains_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Create a New Chain", new_chain_path %></li>
              <% end %>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if logged_in? && current_user.admin? %>
              <li><%= link_to "Create a New Category", new_category_path %></li>
            <% end %>
            <li><%= link_to "All Categories", categories_path %></li>
            <li role="separator" class="divider"></li>
            <% Category.all.each do |category| %>
              <li><%= link_to category.name, category_path(category) %></li>
            <% end %>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About Us", about_path %></li>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <li><%= link_to "Admin Capabilities", admin_path %></li>
          <% end %>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalPositive</title>
    <%= csrf_meta_tags %>

    <!-- Google Fonts Additions -->
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato|Roboto+Condensed:300" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>


    <%= yield %>

  
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
  
</body>
</html>

app/views/pages/about.html.erb
<h1 align="center">About Us</h1>

app/views/pages/admin.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="well">
            <div class="table">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Username</th>
                            <th>Email</th>
                            <th>Admin?</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @users.each do |user| %>
                            <tr>
                                <td><%= user.id %></td>
                                <td><%= user.username %></td>
                                <td><%= user.email %></td>
                                <td><%= user.admin %></td>
                                <td><button onclick="">Change Admin Status</button></td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

app/views/pages/home.html.erb
<h1 align="center">Home Page</h1>

app/views/users/_form.html.erb
<%= form_for @user, url: users_path do |f| %>
    <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control', placeholder: "Enter email" %>
    </div>
    <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
    </div>
    <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm password" %>
    </div>
    <div class="form-group">
        <%= f.label :username %>
        <%= f.text_field :username, class: 'form-control', placeholder: 'Enter username' %>
    </div>
    <div class="form-group">
            <%= f.submit "Sign up", class: 'btn btn-primary pull-left' %>
    </div>
<% end %>

app/views/users/index.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1 align="center">Users</h1>
        <% @users.each do |user| %>
            <div class="well">
                <strong><%= link_to user.username, user_path(user) %></strong>
                <%= pluralize(user.chains.count, "chains") %>
            </div>
        <% end %>
    </div>
</div>

app/views/users/new.html.erb
<div class="row">
    <div class="col-md-4 col-md-offset-1">
        <!-- clearfix extended well downwards to encompass sign-up button -->
        <div class="well clearfix">
            <h1 align="center">Create a New Account</h1>
            <%= render 'form' %>
        </div>
    </div>
    <div class="col-md-4 col-md-offset-1">
        <div class="well">
            <h1 align="center">Log In</h1>
            <%= render 'sessions/signup_login' %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>

<div class="row">
    <% @user_chains.each do |chain| %>
        <div class="col-md-1">
            <div class="well">
                <strong><%= chain.name %></strong> </br>
                <%= chain.pledge %> </br>
                    <%= link_to "Edit Chain", edit_chain_path(chain), class: 'btn btn-xs btn-primary' %>
                    <%= link_to "Delete Chain", chain_path(chain), class: 'btn btn-xs btn-danger', 
                        method: :delete, data: {confirm: "Are you sure?"} %>
            </div>
        </div>
    <% end %>
</div>